name: admin-ui-entity
namespace: official
version: 0.0.2-2
author: Wazo Team
display_name: Entity
min_wazo_version: 18.01
tags:
  - beta
  - internal
homepage: https://github.com/wazo-pbx/wazo-admin-ui-entity
